# Question 1

In [4]:
#importing the numpy package
import numpy as np
#creating a numpuy arrar
array = np.arange(2,51,3)
print(array)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47 50]


# Question 2

In [6]:
#creating 2 lists
list1 = []
list2 = []
#accepting 5 elements in each list
#for list1
for i in range(5):
    x = int(input())
    list1.append(x)
print("list 1 :",list1)
#for list2
for i in range(5):
    y = int(input())
    list2.append(y)
print("list 2 :",list2)
#converting both list into numpy array
array1 = np.array(list1)
array2 = np.array(list2)
print("list 1 converted into array ;",array1)
print("list 2 converted into array ;",array2)
#concatenate both the arrays
con = np.concatenate((array1,array2))
print("the concatenation of the two array is :",con)
#sorting the arrays
sort = np.sort(con)
print("the sorted array is:",sort)
    

5
23
65
78
98
list 1 : [5, 23, 65, 78, 98]
56
78
90
43
21
list 2 : [56, 78, 90, 43, 21]
list 1 converted into array ; [ 5 23 65 78 98]
list 2 converted into array ; [56 78 90 43 21]
the concatenation of the two array is : [ 5 23 65 78 98 56 78 90 43 21]
the sorted array is: [ 5 21 23 43 56 65 78 78 90 98]


# Question 3

In [9]:
#defining the array
array = np.array([[1,6,3],[4,9,8]])
print("the array is :",array)
#finding the dimension of the array 
print("the dimension of array is :",array.ndim)
#finding the size of the array
print("the size of array is:",array.size)

the array is : [[1 6 3]
 [4 9 8]]
the dimension of array is : 2
the size of array is: 6


# Question 4

In [11]:
#definig the array
array = np.arange(int(input()))
#checking the shape of 1D array created 
print("shape of 1D array is:",array.shape)
#converting 1D array into 2D array
array_row = array[np.newaxis]
print("the row of 2d array is :",array_row.shape)
array_col = array[:, np.newaxis]
print("the colum of 2d array is :",array_col.shape)


5
shape of 1D array is: (5,)
the row of 2d array is : (1, 5)
the colum of 2d array is : (5, 1)


# Question5

In [2]:
import numpy as np
#creating square numpy arrays
a = np.array([[2,4],[3,6]])
b = np.array([[9,7],[8,1]])
#vertical stacking 
print('vertical stacking :\n', np.vstack((a,b)))
#horizontal sracking
print('horizontal stacking : \n', np.hstack((a,b)))

vertical stacking :
 [[2 4]
 [3 6]
 [9 7]
 [8 1]]
horizontal stacking : 
 [[2 4 9 7]
 [3 6 8 1]]


# Question 6

In [4]:
array = np.array([4,7,8,9,5,6,4,4])
unique, counts = np.unique(array,return_counts = True)
items= np.asarray((unique,counts)).T
print(items)

[[4 3]
 [5 1]
 [6 1]
 [7 1]
 [8 1]
 [9 1]]
